# Header
menu:
  Home: /
  Prijzen: /prijzen
  Huurvoorwaarden: /huurvoorwaarden
  Contact: /contact


# Title on top left of menu. Leave empty to use main blog title
menu_title: not used

# URL of the Home page image
index_cover: img/home-bg.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# set your own favicon
favicon:

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
mailto: heraldbiewenga@gmail.com